spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME:vanilson}:${MONGO_PASSWORD:vanilson}@${MONGO_HOST:localhost}:27017/notification_db?authSource=admin
