spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: authentication-service

app:
  admin:
    email: ${ADMIN_EMAIL:admin@platform.com}
    password: ${ADMIN_PASSWORD:Admin@123!}
    tenant-id: ${APP_ADMIN_TENANT_ID:system}
