package code.with.vanilson.notification.email;

import code.with.vanilson.notification.kafka.order.OrderConfirmation;
import code.with.vanilson.notification.pdf.InvoicePdfService;
import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.MessageSource;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.thymeleaf.context.Context;
import org.thymeleaf.spring6.SpringTemplateEngine;

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;

import static code.with.vanilson.notification.email.EmailTemplate.ORDER_CONFIRMATION;
import static code.with.vanilson.notification.email.EmailTemplate.PAYMENT_CONFIRMATION;
import static java.nio.charset.StandardCharsets.UTF_8;

/**
 * EmailService — Infrastructure Layer (Messaging)
 * <p>
 * Sends transactional emails (payment confirmation, order confirmation with PDF invoice).
 * <p>
 * KEY CHANGES FROM ORIGINAL:
 * 1. Removed import of code.with.vanilson.productservice.Product — now uses local
 *    OrderConfirmation.ProductSummary DTO. No cross-service JAR dependency.
 * 2. sendOrderConfirmationEmail() now attaches a PDF invoice generated by InvoicePdfService.
 * 3. All log messages resolved from messages.properties via MessageSource.
 * 4. @Async on both methods — email sending never blocks the Kafka consumer thread.
 * 5. Single Responsibility (SOLID-S): only email-sending concerns here.
 * </p>
 *
 * @author vamuhong
 * @version 2.0
 */
@Service
@Slf4j
public class EmailService {

    private static final String SENDER_EMAIL = "noreply@vanilsonshop.io";

    private final JavaMailSender mailSender;
    private final SpringTemplateEngine templateEngine;
    private final InvoicePdfService invoicePdfService;
    private final MessageSource messageSource;

    public EmailService(JavaMailSender mailSender,
                        SpringTemplateEngine templateEngine,
                        InvoicePdfService invoicePdfService,
                        MessageSource messageSource) {
        this.mailSender       = mailSender;
        this.templateEngine   = templateEngine;
        this.invoicePdfService = invoicePdfService;
        this.messageSource    = messageSource;
    }

    /**
     * Sends a payment confirmation email asynchronously.
     * No PDF attachment — payment confirmation is lightweight.
     */
    @Async
    public void sendPaymentSuccessEmail(String destinationEmail, String customerName,
                                         BigDecimal amount, String orderReference) {
        String templateName = PAYMENT_CONFIRMATION.getTemplate();
        log.info(msg("notification.log.sending.payment", destinationEmail, orderReference));

        try {
            MimeMessage mimeMessage = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(
                    mimeMessage, MimeMessageHelper.MULTIPART_MODE_MIXED_RELATED, UTF_8.name());
            helper.setFrom(SENDER_EMAIL);
            helper.setTo(destinationEmail);
            helper.setSubject(PAYMENT_CONFIRMATION.getSubject());

            Map<String, Object> vars = new HashMap<>();
            vars.put("customerName", customerName);
            vars.put("amount", amount);
            vars.put("orderReference", orderReference);

            Context context = new Context();
            context.setVariables(vars);
            helper.setText(templateEngine.process(templateName, context), true);

            mailSender.send(mimeMessage);
            log.info(msg("notification.log.sent.payment", destinationEmail, orderReference));

        } catch (Exception ex) {
            log.error(msg("notification.log.failed.payment", destinationEmail, orderReference,
                    ex.getMessage()));
        }
    }

    /**
     * Sends an order confirmation email with a PDF invoice attached.
     * PDF is generated in-memory by InvoicePdfService and attached as "invoice.pdf".
     */
    @Async
    public void sendOrderConfirmationEmail(String destinationEmail, String customerName,
                                            BigDecimal totalAmount, String orderReference,
                                            OrderConfirmation orderConfirmation) {
        String templateName = ORDER_CONFIRMATION.getTemplate();
        log.info(msg("notification.log.sending.order", destinationEmail, orderReference));

        try {
            MimeMessage mimeMessage = mailSender.createMimeMessage();
            // multipart = true → enables file attachments
            MimeMessageHelper helper = new MimeMessageHelper(
                    mimeMessage, MimeMessageHelper.MULTIPART_MODE_MIXED_RELATED, UTF_8.name());
            helper.setFrom(SENDER_EMAIL);
            helper.setTo(destinationEmail);
            helper.setSubject(ORDER_CONFIRMATION.getSubject());

            Map<String, Object> vars = new HashMap<>();
            vars.put("customerName", customerName);
            vars.put("totalAmount", totalAmount);
            vars.put("orderReference", orderReference);
            vars.put("products", orderConfirmation.products());

            Context context = new Context();
            context.setVariables(vars);
            helper.setText(templateEngine.process(templateName, context), true);

            // Generate and attach PDF invoice
            byte[] invoicePdf = invoicePdfService.generateInvoice(orderConfirmation);
            helper.addAttachment(
                    "invoice-" + orderReference + ".pdf",
                    new org.springframework.core.io.ByteArrayResource(invoicePdf),
                    "application/pdf");

            mailSender.send(mimeMessage);
            log.info(msg("notification.log.sent.order", destinationEmail, orderReference));

        } catch (Exception ex) {
            log.error(msg("notification.log.failed.order", destinationEmail, orderReference,
                    ex.getMessage()));
        }
    }

    private String msg(String key, Object... args) {
        return messageSource.getMessage(key, args, LocaleContextHolder.getLocale());
    }
}
