export const ROUTES = {
  HOME: '/',
  CATALOG: '/catalog',
  PRODUCT: (id: number | string) => `/catalog/${id}`,
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  ACCOUNT: '/account',
  ORDERS: '/account/orders',
  ORDER_DETAIL: (id: number | string) => `/account/orders/${id}`,
  PROFILE: '/account/profile',
  CHECKOUT: '/checkout',
  SELLER: '/seller',
  SELLER_PRODUCTS: '/seller/products',
  SELLER_PRODUCT_NEW: '/seller/products/new',
  SELLER_PRODUCT_EDIT: (id: number | string) => `/seller/products/${id}/edit`,
  SELLER_ORDERS: '/seller/orders',
  SELLER_ORDER_DETAIL: (id: number | string) => `/seller/orders/${id}`,
  SELLER_INVENTORY: '/seller/inventory',
  SELLER_SETTINGS: '/seller/settings',
  ADMIN: '/admin',
  ADMIN_TENANTS: '/admin/tenants',
  ADMIN_TENANT: (id: string) => `/admin/tenants/${id}`,
  ADMIN_USERS: '/admin/users',
  ADMIN_PAYMENTS: '/admin/payments',
  ADMIN_ANALYTICS: '/admin/analytics',
} as const;

export const QUERY_KEYS = {
  PRODUCTS: 'products',
  MY_PRODUCTS: 'my-products',
  PRODUCT: 'product',
  CATEGORIES: 'categories',
  CART: 'cart',
  ORDERS: 'orders',
  SELLER_ORDERS: 'seller-orders',
  ORDER: 'order',
  ORDER_STATUS: 'order-status',
  ORDER_LINES: 'order-lines',
  SELLER_PROFILE: 'seller-profile',
  CUSTOMERS: 'customers',
  CUSTOMER: 'customer',
  PAYMENTS: 'payments',
  TENANTS: 'tenants',
  TENANT: 'tenant',
  TENANT_FLAGS: 'tenant-flags',
  TENANT_USAGE: 'tenant-usage',
} as const;
