---
apiVersion: v1
kind: Service
metadata:
  name: gateway-api-service
  namespace: ecommerce
  labels:
    app: gateway-api-service
spec:
  type: ClusterIP
  selector:
    app: gateway-api-service
  ports:
    - port: 8222
      targetPort: 8222
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: ecommerce
  labels:
    app: authentication-service
spec:
  type: ClusterIP
  selector:
    app: authentication-service
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: ecommerce
  labels:
    app: customer-service
spec:
  type: ClusterIP
  selector:
    app: customer-service
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ecommerce
  labels:
    app: product-service
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce
  labels:
    app: order-service
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ecommerce
  labels:
    app: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: ecommerce
  labels:
    app: cart-service
spec:
  type: ClusterIP
  selector:
    app: cart-service
  ports:
    - port: 8091
      targetPort: 8091
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: ecommerce
  labels:
    app: notification-service
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - port: 8040
      targetPort: 8040
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: ecommerce
  labels:
    app: config-service
spec:
  type: ClusterIP
  selector:
    app: config-service
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: ecommerce
  labels:
    app: discovery-service
spec:
  type: ClusterIP
  selector:
    app: discovery-service
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
      name: http
